### ISSUE TITLE
Scroll speed

### ISSUE THREAD

**Issue by softgears** [asafdav/ng-scrollbar#33]
Hello. 

I am using your scrollbar implemetation in my project. I have a question about scrollspeed when scrolling using mouse wheel. In your implementation, scroll speed is depends on total content size. 
How can I make a fixed scrollspeed (and scroll offset assiciated with one mouse wheel step)?

**Comment by braincomb** [comment]
https://github.com/asafdav/ng-scrollbar/blob/master/src/ng-scrollbar.js#L86 seems to change the scroll speed.

Only problem is the behavior is quite the opposite in Firefox and Chrome. A high value will make it fast in FF but very slow in Chrome, and vice-versa.

@asafdav , any ideas?

**Comment by asafdav** [comment]
You can add a flag that uses a constant value, we can set a different constant for each browser. deltaY will be updated based on the constant and that will give you a fixed scrolling speed. I think it should work, if you want to pull request I'll go over it and merge.
