### ISSUE TITLE
Calculation of page.height

### ISSUE THREAD

**Issue by GBMan** [asafdav/ng-scrollbar#35]
Hi,

I don't understant line 109
```page.height = element[0].offsetHeight - parentOffsetTop;```
I'd patch this when I'd get a negative page.height the same time I had the touchscreen gestion ;)

I use the directive for an other project and I have again a problem whith the page.height.
I think we just need this :
```page.height = element[0].offsetHeight;```

What do you think about it ?

**Comment by asafdav** [comment]
Hi, I will look into it and keep you posted

**Comment by lukaszgrolik** [comment]
When I changed the code as @GBMan suggested, plugin started to work properly for me - before that scrolling containers were too short (too small `height` value of `.ngsb-wrap` element).

**Comment by ProPheT777** [comment]
> `page.height = element[0].offsetHeight;`

+1 you don't need to substract the parentOffsetTop

**Comment by od0** [comment]
Just ran into this issue myself. I had problems in particular with using ng-scrollbar for a dashboard layout where there were multiple scrollbars stacked vertically. Simplifying to ```page.height = element[0].offsetHeight;``` resolved the issue for me as well.
