### ISSUE TITLE
Show scrollbar on hover

### ISSUE THREAD

**Issue by ritz078** [asafdav/ng-scrollbar#42]
Is there any way to show the scrollbar only on hover ?

**Comment by asafdav** [comment]
Yes, just extend the css

**Comment by gayanvirajith** [comment]
Thanks for the great module. It really awesome! 

Not sure this is right method, but i managed to show the scrollbar on hover by extending the css class as follows:
````
/*
 * ng-scrollbar show scrollbar when hover
 */
 .ngsb-wrap .ngsb-scrollbar {
  width: 16px;
  height: 100%;
  top: 0;
  right: 0;
  opacity: 0;
  filter: "alpha(opacity=0)";
  -ms-filter: "alpha(opacity=0)";
  transition: opacity .1s linear; // Add bit of transition (todo: browser prefix)
  /* old ie */
}
````

**Comment by asafdav** [comment]
Looks great, if you want you can update the README so others can benefit
from this.
